In [14]:
import torch

In [20]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3256, 0.0203, 0.1801],
        [0.9135, 0.2179, 0.0983],
        [0.4498, 0.8054, 0.7162],
        [0.4775, 0.1610, 0.5596],
        [0.6815, 0.2613, 0.8034]])


In [16]:
# -*- coding: utf-8 -*-
import numpy as np
import math

# Create random input and output data
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

# Randomly initialize weights
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y
    # y = a + b x + c x^2 + d x^3
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d

print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')

99 251.82605506244857
199 180.11762765437345
299 129.59853135241798
399 93.99757735685662
499 68.90300172431773
599 51.20991099849156
699 38.732428058280185
799 29.931188940194183
899 23.721803137941524
999 19.34016823568444
1099 16.247726925955774
1199 14.064797118104819
1299 12.52364092585593
1399 11.435417870774426
1499 10.666907708796145
1599 10.124110005941102
1699 9.740685763432497
1799 9.469809463898768
1899 9.278423886556999
1999 9.143188223067801
Result: y = 0.018949041108958547 + 0.8590293799524515 x + -0.003269024904700425 x^2 + -0.09365591348283477 x^3


In [21]:
x = torch.empty(5,3)
x

tensor([[0.4453, 0.3571, 0.8356],
        [0.3510, 0.9311, 0.9451],
        [0.4680, 0.8011, 0.1743],
        [0.3091, 0.1565, 0.3492],
        [0.9893, 0.8531, 0.8662]])

In [23]:
x = torch.rand(5,3)
x

tensor([[0.4785, 0.1382, 0.9641],
        [0.6788, 0.5779, 0.7854],
        [0.9055, 0.3945, 0.6451],
        [0.6037, 0.1403, 0.9708],
        [0.2772, 0.4708, 0.8714]])

In [25]:
x= torch .zeros(5,3,dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [26]:
x = torch.tensor([5,5,3])

In [28]:
x.size()

torch.Size([3])

In [31]:
a = torch.ones(5)
b = a.numpy()

In [34]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [46]:
x = torch.randn(3,4,requires_grad= True)
x
x= torch.randn(3,4)
x.requirements_grad = True
x

tensor([[ 1.3748, -0.6618,  0.0023,  1.5587],
        [-1.9087,  0.4491, -0.5414,  1.0327],
        [ 0.9487, -0.5854,  0.8525,  0.9065]])

In [38]:
b = torch.randn(3,4,requires_grad = True)

In [40]:
t = x +b

In [41]:
y = t.sum()
y

tensor(-2.7340, grad_fn=<SumBackward0>)

In [42]:
y.backward()

In [43]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [47]:
x.requires_grad, b.requires_grad,t.requires_grad

(False, True, True)

In [50]:
x = torch.rand(1)
b = torch.rand(1,requires_grad = True)
w = torch.rand(1, requires_grad = True)
y = w*x
z = y+b

In [52]:
x.requires_grad,b.requires_grad,w.requires_grad,y.requires_grad

(False, True, True, True)

In [67]:
z.backward(retain_graph = True)

In [69]:
w.grad

tensor([1.3033])

In [70]:
b.grad

tensor([2.])

In [17]:
x_values = [i for i in range(11)]
x_train = np.array(x_values,dtype = np.float32)
x_train = x_train.reshape(-1,1)
x_train.shape

(11, 1)

In [19]:
y_values = [2*i +1 for i in x_values]
y_train = np.array(y_values, dtype = np.float32)
y_train = y_train.reshape(-1,1) 
y_train.shape

(11, 1)

In [2]:
import torch 
import torch.nn as nn

In [8]:
class LinearRegressionModel(nn.Module):
    def __init__ (self, input_dim, output_dim):
        super(LinearRegressionModel,self).__init__()
        self.linear = nn.Linear(input_dim,output_dim)#1,1
        
    def forward(self, x):
        out = self.linear(x)
        return out

In [11]:
model

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [9]:
input_dim = 1
output_dim = 1
model = LinearRegressionModel(input_dim, output_dim)

In [12]:
epochs = 1000
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(),lr= learning_rate)
criterion = nn.MSELoss()

In [24]:
for epoch in range(epochs):
    epoch += 1
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)
    
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    if epoch%50 == 0:
        print('epoch {}, loss {}'.format(epoch,loss.item()))

epoch 50, loss 0.03659121319651604
epoch 100, loss 0.02087031863629818
epoch 150, loss 0.011903678998351097
epoch 200, loss 0.0067894067615270615
epoch 250, loss 0.0038724506739526987
epoch 300, loss 0.0022086917888373137
epoch 350, loss 0.0012597376480698586
epoch 400, loss 0.0007185069262050092
epoch 450, loss 0.0004097999189980328
epoch 500, loss 0.00023373495787382126
epoch 550, loss 0.0001333207474090159
epoch 600, loss 7.603902486152947e-05
epoch 650, loss 4.336854908615351e-05
epoch 700, loss 2.473661515978165e-05
epoch 750, loss 1.41088703458081e-05
epoch 800, loss 8.04998489911668e-06
epoch 850, loss 4.591096967487829e-06
epoch 900, loss 2.6180423446930945e-06
epoch 950, loss 1.4931254099792568e-06
epoch 1000, loss 8.518538834323408e-07


In [25]:
torch.save(model.state_dict(),'model.pkl')

In [29]:
model.load_state_dict(torch.load('model.pkl'))

<All keys matched successfully>

In [33]:
import torch
import torch.nn as nn 
import numpy as np

class LinearRegressionModel(nn.Module):
    def __init__ (self, input_dim, output_dim):
        super(LinearRegressionModel,self).__init__()
        self.linear = nn.Linear(input_dim,output_dim)#1,1
        
    def forward(self, x):
        out = self.linear(x)
        return out

input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)

criterion = nn.MSELoss()

learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

epochs = 1000

for epoch in range(epochs):
    epoch += 1
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)
    
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    if epoch%50 == 0:
        print('epoch {}, loss {}'.format(epoch,loss.item()))

epoch 50, loss 0.025402583181858063
epoch 100, loss 0.014488649554550648
epoch 150, loss 0.008263759315013885
epoch 200, loss 0.004713339265435934
epoch 250, loss 0.0026883056852966547
epoch 300, loss 0.0015332918846979737
epoch 350, loss 0.0008745459490455687
epoch 400, loss 0.0004987961146980524
epoch 450, loss 0.00028450004174374044
epoch 500, loss 0.00016226369189098477
epoch 550, loss 9.255756594939157e-05
epoch 600, loss 5.278818207443692e-05
epoch 650, loss 3.010629370692186e-05
epoch 700, loss 1.7173158994410187e-05
epoch 750, loss 9.794047400646377e-06
epoch 800, loss 5.587169653153978e-06
epoch 850, loss 3.1864087759458926e-06
epoch 900, loss 1.8174723663832992e-06
epoch 950, loss 1.0363369256083388e-06
epoch 1000, loss 5.912046958655992e-07


In [43]:
import torch 
import numpy as np
x = torch.rand(2,2)
y = torch.rand(2,2)
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device= device)
    y = torch.ones(5)
    y = y.to(device)
    z = z.to("cpu")
    z = x + y
    z.numpy()
    
x = torch.ones(5,requires_grad= True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [47]:
import torch

x = torch.randn(3,requires_grad= True)
print(x)

y = x+2
z = y*y*2
print(y)
#z = z.mean()
print(z)

v = torch.tensor([0.1,1.0,0.001],dtype = torch.float32 )
z.backward(v)
print(x.grad)

tensor([ 0.5800, -1.9704, -0.4358], requires_grad=True)
tensor([2.5800, 0.0296, 1.5642], grad_fn=<AddBackward0>)
tensor([1.3313e+01, 1.7542e-03, 4.8934e+00], grad_fn=<MulBackward0>)
tensor([1.0320, 0.1185, 0.0063])


In [52]:
import torch

x = torch.randn(3,requires_grad= True)
x.requires_grad_(False)
print(x)

tensor([-2.0547, -0.9548,  1.2717])


In [57]:
import torch

weights = torch.ones(4,requires_grad= True)
for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [58]:
import torch 
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0,requires_grad= True)

y_hat = w*x
loss = (y_hat - y )**2

loss.backward()
print(w.grad)



tensor(-2.)


In [3]:
import torch
model = torch.hub.load('pytorch/vision:v0.4.2','deeplabv3_resnet101',pretrained = True)
model.val()

Using cache found in /Users/jonah/.cache/torch/hub/pytorch_vision_v0.4.2


AttributeError: 'DeepLabV3' object has no attribute 'val'